### ISSUE TITLE
Receiving a 403 Unauthorized response for all tests on htaccess.madewithlove.com

### ISSUE THREAD

**Issue by linuxwebexpert** [madewithlove/htaccess.madewithlove.be#94]
**Describe the bug**
Whenever I try to test my .htaccess rules with a sample input URL, I get a 403 Unauthorized response in the console. It does not currently check anything and returns the following console output using the Inspector. I have also tried with private icognitor windows to prevent any of my extensions from interfering.
            
            
```
POST https://htaccess.madewithlove.com/api 403 (Forbidden)
s @ useHtaccessApi.ts:11
onSubmit @ Form.tsx:70
Dc @ react-dom-client.production.js:11858
(anonymous) @ react-dom-client.production.js:12410
Dt @ react-dom-client.production.js:1470
Vc @ react-dom-client.production.js:11996
ld @ react-dom-client.production.js:14699
ad @ react-dom-client.production.js:14667
VM50:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

**Expected behavior**
I expect the online tester to work as it has in the past. This was the best validation tool ever. I would be happy to host an online validator. If you've abandoned this project, please provide source code.

**Reproduce link**
https://htaccess.madewithlove.com/

**Comment by jonasvogel** [comment]
Same on our end (`POST https://htaccess.madewithlove.com/api 403 (Forbidden)`). Highly appreciated to get the tool back online. 🫶

**Comment by WouterSioen** [comment]
I'm looking into it

**Comment by WouterSioen** [comment]
A fix has been deployed, and you can use the tool again as before. Thanks for reporting the issue!

**Comment by jonasvogel** [comment]
@WouterSioen  I still get a 403 for a POST to `https://htaccess.madewithlove.com/api` right now - can you check again? Thank you.

**Comment by WouterSioen** [comment]
Hmm, very weird, it works on my end.

The problem was related to a cookie-related rule that was set too strict. Would you mind trying clearing your cookies and testing again to see if that helps? If that's the case, I'll check if I can make our blocking rules a tad less strict.

**Comment by WouterSioen** [comment]
Okay, it looks like it worked with small htaccess files (which I used to test), but not with bigger ones. I adapted some server rules and this should now work with more complex payloads as well.
